### ISSUE TITLE
I frame seems to no longer be working

### ISSUE THREAD

**Issue by stw222** [nikilok/meteo-map-viewer#1]
This might just be a case of me not having used the software since the cannonball
when i do yarn start and it opens in a web browser, then i use my custom url which includes my username,
nothing seems to appear except for the plane icon overlay
`http://localhost:3000/?user=stw222`

I can also confirm that i appear normally on simair

**Comment by nikilok** [comment]
Do you have your CORS enabling browser plugins enabled on your browser?
I just checked, and it seems to be working fine for me.
![image](https://user-images.githubusercontent.com/6220175/108275738-11e1f500-7177-11eb-931d-db9c36fb7f23.png)

**Comment by stw222** [comment]
...
i forgot about that...
thanks for reminding me
i knew it would be user error since i hadnt used this in so long
